/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../src/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/Layout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/VendorDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AdminLogin`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/VendorRegistration`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/lib/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/Layout`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/AdminDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/VendorDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/AdminLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/VendorRegistration`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../vite.config${`?${string}` | `#${string}` | ''}` | `/../src/App${`?${string}` | `#${string}` | ''}` | `/../src/main${`?${string}` | `#${string}` | ''}` | `/../src/lib/supabase${`?${string}` | `#${string}` | ''}` | `/../src/components/Layout${`?${string}` | `#${string}` | ''}` | `/../src/components/AdminDashboard${`?${string}` | `#${string}` | ''}` | `/../src/components/VendorDashboard${`?${string}` | `#${string}` | ''}` | `/../src/components/AdminLogin${`?${string}` | `#${string}` | ''}` | `/../src/components/VendorRegistration${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chatbot${`?${string}` | `#${string}` | ''}` | `/chatbot${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/itinerary${`?${string}` | `#${string}` | ''}` | `/itinerary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/marketplace${`?${string}` | `#${string}` | ''}` | `/marketplace${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../src/lib/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/Layout`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/VendorDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/AdminLogin`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/VendorRegistration`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chatbot` | `/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/itinerary` | `/itinerary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/marketplace` | `/marketplace`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
